import Foundation

extension TCG {
    public enum Rarity: String, Codable, Hashable, Sendable {
        case aceSpecRare = "ACE SPEC Rare"
        case amazingRare = "Amazing Rare"
        case classicCollection = "Classic Collection"
        case common = "Common"
        case doubleRare = "Double Rare"
        case hyperRare = "Hyper Rare"
        case illustrationRare = "Illustration Rare"
        case legend = "LEGEND"
        case promo = "Promo"
        case radiantRare = "Radiant Rare"
        case rare = "Rare"
        case rareAce = "Rare ACE"
        case rareBreak = "Rare BREAK"
        case rareHolo = "Rare Holo"
        case rareHoloEx = "Rare Holo EX"
        case rareHoloGx = "Rare Holo GX"
        case rareHoloLvX = "Rare Holo LV.X"
        case rareHoloStar = "Rare Holo Star"
        case rareHoloV = "Rare Holo V"
        case rareHoloVmax = "Rare Holo VMAX"
        case rareHoloVstar = "Rare Holo VSTAR"
        case rarePrime = "Rare Prime"
        case rarePrismStar = "Rare Prism Star"
        case rareRainbow = "Rare Rainbow"
        case rareSecret = "Rare Secret"
        case rareShining = "Rare Shining"
        case rareShiny = "Rare Shiny"
        case rareShinyGx = "Rare Shiny GX"
        case rareUltra = "Rare Ultra"
        case shinyRare = "Shiny Rare"
        case shinyUltraRare = "Shiny Ultra Rare"
        case specialIllustrationRare = "Special Illustration Rare"
        case trainerGalleryRareHolo = "Trainer Gallery Rare Holo"
        case ultraRare = "Ultra Rare"
        case uncommon = "Uncommon"
    }
}
